language: cpp

before_script:
    - export _PROJECT_NAME=$(cat .project_name)
    - export _PROJECT_VERSION=$(cat .version)
    - export _PROJECT_DEB_NAME="$_PROJECT_NAME-$_PROJECT_VERSION.$TRAVIS_BUILD_NUMBER-Linux.deb"
    - sudo apt-get install libboost-test-dev libtclap-dev -y 

script:
    - cmake .
    - cmake --build .
    - cmake --build . --target test
    - cmake --build . --target package

deploy:
    provider: script
    skip_cleanup: true
    script:
        - curl -s -T $_PROJECT_DEB_NAME -umalegkin:$BINTRAY_API_KEY "https://api.bintray.com/content/om2/otus/$_PROJECT_NAME/$_PROJECT_VERSION/$_PROJECT_DEB_NAME;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" | grep -v success && exit 1 || exit 0

